ALTER TABLE WORK_ORDER ADD COLUMN OFFICE_CODE VARCHAR (10);
ALTER TABLE PERSON ADD COLUMN IS_FROM_POOL VARCHAR (1) DEFAULT 'N';

UPDATE WORK_ORDER SET OFFICE_CODE = ( 
    SELECT OFFICE_CODE FROM PERSON WHERE WORK_ORDER.VENTURE_ID = ID);
