INSERT INTO CODE_REFERENCE (CODE_TABLE, CODE, PARAM_CHARVAL) VALUES ("RANK","YOU","Nowicjusz");
INSERT INTO CODE_REFERENCE (CODE_TABLE, CODE, PARAM_CHARVAL) VALUES ("RANK","REG","Regular");
INSERT INTO CODE_REFERENCE (CODE_TABLE, CODE, PARAM_CHARVAL) VALUES ("RANK","SEN","Senior");

ALTER TABLE PERSON ADD COLUMN RANK_CODE VARCHAR (10);
ALTER TABLE PERSON ADD COLUMN AGREEMENT_CODE VARCHAR (10);
ALTER TABLE PERSON ADD COLUMN IS_FROM_POOL VARCHAR (1);
