INSERT INTO CODE_REFERENCE (CODE_TABLE, CODE, PARAM_INTVAL, PARAM_CHARVAL) VALUES ("WORK_STATUS","CA", 8, "Anulowane");

UPDATE WORK_ORDER SET STATUS_CODE = 'IS' WHERE STATUS_CODE = 'AC';

DELETE FROM CODE_REFERENCE WHERE CODE = 'AC';