DROP TABLE IF EXISTS PAYROLL;
CREATE TABLE PAYROLL (
	PERSON_ID INTEGER NOT NULL,
	PERIOD_DATE INTEGER NOT NULL,
    LEAVE_TIME INTEGER NOT NULL,
	WORK_TIME INTEGER NOT NULL,
    POOL_WORK_TIME INTEGER NOT NULL,
    NONPOOL_WORK_TIME INTEGER NOT NULL,
    OVER_TIME INTEGER NOT NULL,
    LEAVE_DUE INTEGER NOT NULL,
    WORK_DUE INTEGER NOT NULL,
	OVER_DUE INTEGER NOT NULL,
	TOTAL_DUE INTEGER NOT NULL,
	IS_FROM_POOL VARCHAR(1) NOT NULL,
	RANK_CODE VARCHAR(10) NOT NULL,
	PROJECT_FACTOR REAL,
    BUDGET REAL,
    POOL_RATE REAL,
	OVER_TIME_FACTOR REAL,
	APPROVED VARCHAR(1) NOT NULL,
	LAST_MOD INTEGER,
	MODIFIED_BY INTEGER, 
	UNIQUE (PERSON_ID, PERIOD_DATE) ,
	FOREIGN KEY(PERSON_ID) REFERENCES PERSON(ID)
);


DROP INDEX IF EXISTS PAYROLL_PID_IDX;
DROP INDEX IF EXISTS PAYROLL_PD_IDX;
CREATE INDEX PAYROLL_PID_IDX ON PAYROLL(PERSON_ID);
CREATE INDEX PAYROLL_PD_IDX ON PAYROLL(PERIOD_DATE);

DROP TRIGGER IF EXISTS SET_TIMING_PAYROLL;
CREATE TRIGGER SET_TIMING_PAYROLL AFTER INSERT ON PAYROLL
BEGIN
	UPDATE PAYROLL
	SET LAST_MOD = STRFTIME('%s','NOW')
	WHERE PERSON_ID = NEW.PERSON_ID AND PERIOD_DATE = NEW.PERIOD_DATE;
END;
