CREATE TABLE SEQUENCER (
    SEQ_NAME VARCHAR (10) NOT NULL,
    SEQ_VAL  INTEGER      NOT NULL,
    UNIQUE (SEQ_NAME, SEQ_VAL)
);

INSERT INTO SEQUENCER (SEQ_NAME,SEQ_VAL) VALUES ('WO_SEQ',4000);
INSERT INTO SEQUENCER (SEQ_NAME,SEQ_VAL) VALUES ('PROTOCOL_NO_SEQ',1000);