ALTER TABLE PERSON ADD COLUMN RANK_CODE VARCHAR (10);
ALTER TABLE PERSON ADD COLUMN AGREEMENT_CODE VARCHAR (10);
ALTER TABLE PERSON ADD COLUMN IS_FROM_POOL VARCHAR (1);
ALTER TABLE PERSON ADD COLUMN SALARY INT;
ALTER TABLE PERSON ADD COLUMN SALARY_RATE INT;
ALTER TABLE PERSON ADD COLUMN LEAVE_RATE INT;


UPDATE PERSON
	SET IS_FROM_POOL = "N";
	
UPDATE PERSON
	SET PROJECT_FACTOR = 1;
	
UPDATE PERSON SET RANK_CODE = "YOU" WHERE POSITION IN ("praktykant", "asystent projektanta");
UPDATE PERSON SET RANK_CODE = "REG" WHERE POSITION IN ("specjalista", "inżynier", "projektant"); 
UPDATE PERSON SET RANK_CODE = "SEN" WHERE POSITION IN ("starszy projektant","kierownik");
UPDATE PERSON SET RANK_CODE = "DZI" WHERE ID IN (55,56,58,63,64,74,76,77);


UPDATE PERSON SET RANK_CODE = "REG" WHERE ID IN (79,141,144,145,146); 



 