ALTER TABLE WORK_ORDER ADD COLUMN OFFICE_CODE VARCHAR (10);
ALTER TABLE WORK_ORDER ADD COLUMN IS_FROM_POOL VARCHAR (1) DEFAULT 'Y';
ALTER TABLE WORK_ORDER ADD COLUMN MODIFIED_BY INTEGER;

UPDATE WORK_ORDER SET OFFICE_CODE = ( 
    SELECT OFFICE_CODE FROM PERSON WHERE WORK_ORDER.VENTURE_ID = ID);
UPDATE WORK_ORDER SET IS_FROM_POOL = 'Y';
UPDATE WORK_ORDER SET MODIFIED_BY = 137;