{
 "title": "Bot app",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Time of the last metrics collection",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "last_time",
   "targets": [
    { "expr": "botapp_nodejs_version_info" }
   ]
  },
  {
   "title": "Node version",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    { "expr": "botapp_nodejs_version_info", "legendFormat": "{{version}}" }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "dateTimeFromNow",
   "valueName": "current",
   "targets": [
    {
     "expr": "botapp_process_start_time_seconds*1000"
    }
   ]
  },
  {
   "title": "Payroll scheduler",
   "type": "graph",
   "description": "Number of payroll records updated. Value will be reset on application restart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "botapp_payroll_scheduler" }
   ]
  },
  {
   "title": "Nodejs event loop lag",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "botapp_nodejs_eventloop_lag_seconds",
     "legendFormat": "lag"
    }
   ]
  },
  {
   "title": "Active request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "botapp_nodejs_active_requests_total"
    }
   ]
  },
  {
   "title": "Nodejs heap size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "botapp_nodejs_heap_size_total_bytes/(1024*1024)",
     "legendFormat": "total"
    },
    {
     "expr": "botapp_nodejs_heap_size_used_bytes/(1024*1024)",
     "legendFormat": "used"
    }
   ]
  },
  {
   "title": "System CPU seconds",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "botapp_process_cpu_system_seconds_total",
     "legendFormat": "system"
    },
    {
     "expr": "botapp_process_cpu_user_seconds_total ",
     "legendFormat": "user"
    }
   ]
  },
  {
   "title": "System memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 12 },
   "yaxes": [
    { "format": "decmbytes" }
   ],
   "targets": [
    {
     "expr": "botapp_process_resident_memory_bytes/(1024*1024)",
     "legendFormat": "resident"
    },
    {
     "expr": "botapp_process_heap_bytes/(1024*1024)",
     "legendFormat": "heap"
    },
    {
     "expr": "botapp_process_virtual_memory_bytes/(1024*1024)",
     "legendFormat": "virtual"
    }
   ]
  }
 ]
}