WITH ALL_WO AS (
    SELECT ID, WORK_NO, STATUS_CODE, TYPE_CODE, OFFICE_CODE, COMPLEXITY_CODE, COMPLEXITY, DESCRIPTION, COMMENT, MD_CAPEX, PRICE, PROTOCOL_NO, IS_FROM_POOL, CREATED, LAST_MOD, MODIFIED_BY, ITEM_ID, VENTURE_ID, 'WO' STYPE, DATETIME(LAST_MOD,'unixepoch') LAST_MOD_TXT
    FROM WORK_ORDER
    UNION ALL
    SELECT ID, WORK_NO, STATUS_CODE, TYPE_CODE, OFFICE_CODE, COMPLEXITY_CODE, COMPLEXITY, DESCRIPTION, COMMENT, MD_CAPEX, PRICE, PROTOCOL_NO, IS_FROM_POOL, CREATED, LAST_MOD, MODIFIED_BY, ITEM_ID, VENTURE_ID, 'WOH' STYPE, DATETIME(LAST_MOD,'unixepoch') LAST_MOD_TXT
    FROM WORK_ORDER_HIST
)
-- WO ID WHERE NO 'CO' WAS FOUND
, GRP_IDS AS (
    SELECT ID
    FROM ALL_WO
    GROUP BY ID
    HAVING 
        MAX( CASE STATUS_CODE  WHEN 'IS' THEN 1 ELSE 0 END ) = 1
        AND MAX( CASE STATUS_CODE  WHEN 'CO' THEN 1 ELSE 0 END ) = 0
)
, WO_IS_DATE AS (
    SELECT AW.ID, MAX(LAST_MOD) LAST_MOD, DATETIME(MAX(LAST_MOD),'unixepoch') LAST_MOD_TXT
    FROM ALL_WO AW
    WHERE AW.STATUS_CODE = 'IS' AND AW.ID IN (SELECT ID FROM GRP_IDS)
    GROUP BY AW.ID
)
, WO_IS AS(
    SELECT AW.ID, AW.WORK_NO, 'CO' STATUS_CODE, AW.TYPE_CODE, AW.OFFICE_CODE, AW.COMPLEXITY_CODE, AW.COMPLEXITY, AW.DESCRIPTION, AW.COMMENT, AW.MD_CAPEX, AW.PRICE, AW.PROTOCOL_NO, AW.IS_FROM_POOL, AW.CREATED, (WIS.LAST_MOD - 1) LAST_MOD, STRFTIME('%s','now') HIST_CREATED ,AW.MODIFIED_BY, AW.ITEM_ID, AW.VENTURE_ID
    FROM ALL_WO AW, WO_IS_DATE WIS
    WHERE AW.ID = WIS.ID AND AW.LAST_MOD = WIS.LAST_MOD 
)

INSERT INTO WORK_ORDER_HIST (
   WORK_NO, STATUS_CODE, TYPE_CODE, OFFICE_CODE, COMPLEXITY_CODE, COMPLEXITY, DESCRIPTION, COMMENT, MD_CAPEX, PRICE, PROTOCOL_NO, IS_FROM_POOL, CREATED, LAST_MOD, HIST_CREATED, MODIFIED_BY, ITEM_ID, VENTURE_ID 
)
SELECT WORK_NO, STATUS_CODE, TYPE_CODE, OFFICE_CODE, COMPLEXITY_CODE, COMPLEXITY, DESCRIPTION, COMMENT, MD_CAPEX, PRICE, PROTOCOL_NO, IS_FROM_POOL, CREATED, LAST_MOD, HIST_CREATED, MODIFIED_BY, ITEM_ID, VENTURE_ID FROM WO_IS



--SELECT * FROM ALL_WO
--SELECT * FROM WO_IS_DATE WHERE 1527803999 <= LAST_MOD 
--WHERE ID = 4286



-- SELECT STRFTIME('%s','2018-05-31T23:59:59','utc') TD