DROP TRIGGER IF EXISTS ADD_MISSING_CO_RECORD;

CREATE TRIGGER ADD_MISSING_CO_RECORD AFTER UPDATE ON WORK_ORDER
WHEN
    NEW.STATUS_CODE = 'IS'
BEGIN
    INSERT INTO WORK_ORDER_HIST ( ID, WORK_NO, STATUS_CODE, TYPE_CODE, OFFICE_CODE, COMMENT, MD_CAPEX, PROTOCOL_NO, IS_FROM_POOL, DESCRIPTION, COMPLEXITY_CODE, COMPLEXITY, PRICE, ITEM_ID, VENTURE_ID, MODIFIED_BY, CREATED, LAST_MOD, HIST_CREATED )
    SELECT NEW.ID, NEW.WORK_NO, 'CO', NEW.TYPE_CODE, NEW.OFFICE_CODE, NEW.COMMENT, NEW.MD_CAPEX, NEW.PROTOCOL_NO, NEW.IS_FROM_POOL, NEW.DESCRIPTION, NEW.COMPLEXITY_CODE, NEW.COMPLEXITY, NEW.PRICE, NEW.ITEM_ID, NEW.VENTURE_ID, NEW.MODIFIED_BY, NEW.CREATED, NEW.LAST_MOD, STRFTIME('%s','NOW') 
    WHERE NOT EXISTS ( SELECT 1 FROM WORK_ORDER_HIST 
                                WHERE ID = NEW.ID AND STATUS_CODE = 'CO');                                
END;
