--Katarzyna Dzierżyk 67
--Paweł Romaniak 66
--Wiktor Waltrowski 78

UPDATE PERSON SET IS_FROM_POOL = 'Y'
WHERE ID IN (66, 67, 78) ;

UPDATE WORK_ORDER SET IS_FROM_POOL = 'Y'
WHERE ID IN (
    SELECT WO.ID --, DATETIME(LAST_MOD,'unixepoch') LAST_MOD_TXT, WO.STATUS_CODE, WO.IS_FROM_POOL, WO.OFFICE_CODE
    FROM WORK_ORDER WO JOIN PERSON_WO PW ON WO.ID = PW.WO_ID JOIN PERSON P ON PW.PERSON_ID = P.ID 
        JOIN WORK_TYPE WT ON WO.OFFICE_CODE = WT.OFFICE_CODE AND WO.TYPE_CODE = WT.TYPE_CODE AND WO.COMPLEXITY_CODE = WT. COMPLEXITY_CODE
    WHERE P.ID IN (66,67,78)
    AND WT.IS_FROM_POOL =  'Y'
    AND WO.LAST_MOD > STRFTIME('%s','2018-04-01T00:00:00','utc')
    --ORDER BY 3, 2
);


UPDATE WORK_ORDER_HIST SET IS_FROM_POOL = 'Y'
WHERE ID IN (
    SELECT WO.ID --, DATETIME(LAST_MOD,'unixepoch') LAST_MOD_TXT, WO.STATUS_CODE, WO.IS_FROM_POOL, WO.OFFICE_CODE
    FROM WORK_ORDER_HIST WO JOIN PERSON_WO PW ON WO.ID = PW.WO_ID JOIN PERSON P ON PW.PERSON_ID = P.ID 
        JOIN WORK_TYPE WT ON WO.OFFICE_CODE = WT.OFFICE_CODE AND WO.TYPE_CODE = WT.TYPE_CODE AND WO.COMPLEXITY_CODE = WT. COMPLEXITY_CODE
    WHERE P.ID IN (66,67,78)
    AND WT.IS_FROM_POOL =  'Y'
    AND WO.LAST_MOD > STRFTIME('%s','2018-04-01T00:00:00','utc')
--    ORDER BY 3, 2
)