CREATE UNIQUE INDEX INITIALS_IDX ON PERSON(INITIALS);
	
DROP TABLE IF EXISTS IMPORT_LOG;
CREATE TABLE IMPORT_LOG (
   TXT VARCHAR(1000)
);	



DROP TABLE IF EXISTS LINK;
CREATE TABLE LINK (
	PERSON VARCHAR(200),
	ITEM_NO VARCHAR(200),
	PRICE VARCHAR(200),
	HANDOVER VARCHAR(200),
	FINISH VARCHAR(200)
);