DELETE FROM PERSON_WO WHERE PERSON_ID = 1 AND WO_ID = 1
rollback

SELECT PERSON_ID, USED_TIME, WORK_DATE, STRFTIME('%Y-%m-%d',DATETIME(WORK_DATE,"unixepoch")),DATETIME(WORK_DATE,"%Y-%m-%d"), DATE(WORK_DATE),  DATE('now') FROM TIME_SHEET WHERE 1=1  AND (WORK_DATE/86400) >= (STRFTIME("%s","2016-01-01")/86400)


SELECT PERSON_ID, USED_TIME, DATETIME(WORK_DATE,'unixepoch'), WORK_DATE/86400
FROM TIME_SHEET

SELECT STRFTIME('%s','2016-11-11 00:00:00') AS DATE_STR, (STRFTIME('%s','2016-11-11 00:00:00') / 86400) AS DATE_IN_DAYS
SELECT STRFTIME('%Y-%m-%d','2016-11-11 01:01:00')
SELECT STRFTIME('%s','2016-11-11 23:59:59') - STRFTIME('%s','2016-11-11 01:01:00')
SELECT 60*60*24

SELECT STRFTIME('%s','2016-11-11 23:59:59')
SELECT STRFTIME('%s','2016-11-11 00:00:00')
SELECT STRFTIME('%s','2016-11-11')
SELECT STRFTIME('%s','2016-11-11 00:00:00'), (STRFTIME('%s','2016-11-11 00:00:00')/86400)*86400, DATETIME((STRFTIME('%s','2016-10-11 00:00:00')/86400)*86400,'unixepoch')
SELECT STRFTIME('%Y-%m-%d','2016-11-11 01:01:00')

SELECT P.ID AS PERSON_ID, (SELECT COALESCE( SUM(USED_TIME), 0) AS USED_TIME FROM TIME_SHEET AS TS WHERE TS.PERSON_ID = P.ID AND (WORK_DATE/86400) <= (STRFTIME("%s","2016-11-12")/86400)) AS USED_TIME FROM PERSON AS P



        workDateBefore: 'AND WORK_DATE <= STRFTIME("%%s","%(workDateBefore)s")',
        workDateAfter: 'AND WORK_DATE >= STRFTIME("%%s","%(workDateAfter)s")',
        
rollback;
begin;
INSERT INTO TIME_SHEET (PERSON_ID, WORK_DATE, USED_TIME) VALUES ("15", STRFTIME("%s","2017-11-11"), "5");
commit;

WITH PARAMS AS (SELECT STRFTIME('%s','2017-11-20') AS AFTER_DATE, STRFTIME('%s','2017-11-22') AS BEFORE_DATE)

SELECT WOS.ID AS WO_ID, WOS.WORK_NO AS WO_WORK_NO, WOS.DONE_DATE AS WO_DONE_DATE, WOS.ASSIGNED_DATE AS WO_ASSIGNED_DATE, WOS.STATUS_CODE AS WO_STATUS_CODE,
         P.EMAIL AS PERSON_EMAIL, P.FIRST_NAME AS PERSON_FIRST_NAME, P.LAST_NAME AS PERSON_LAST_NAME, P.OFFICE_CODE AS PERSON_OFFICE_CODE, P.ROLE_CODE AS PERSON_ROLE_CODE
FROM
(SELECT ID, WORK_NO, CASE STATUS_CODE WHEN 'CO' THEN DATETIME(LAST_MOD,'unixepoch') ELSE null END AS DONE_DATE, STATUS_CODE, DATETIME(PWO.CREATED,'unixepoch') AS ASSIGNED_DATE, PWO.PERSON_ID
FROM WORK_ORDER AS WO JOIN PERSON_WO AS PWO ON WO.ID = PWO.WO_ID 
WHERE (STATUS_CODE = 'CO' AND LAST_MOD/86400 BETWEEN (SELECT AFTER_DATE/86400 FROM PARAMS) AND (SELECT BEFORE_DATE/86400 FROM PARAMS))
    OR (WO.STATUS_CODE IN ('AS') AND PWO.CREATED/86400 BETWEEN (SELECT AFTER_DATE/86400 FROM PARAMS) AND (SELECT BEFORE_DATE/86400 FROM PARAMS) )
UNION
SELECT ID, WORK_NO, CASE STATUS_CODE WHEN 'CO' THEN DATETIME(LAST_MOD,'unixepoch') ELSE null END AS DONE_DATE, STATUS_CODE, DATETIME(PWO.CREATED,'unixepoch') AS ASSIGNED_DATE, PWO.PERSON_ID
FROM WORK_ORDER_HIST AS WO JOIN PERSON_WO AS PWO ON WO.ID = PWO.WO_ID
WHERE (STATUS_CODE = 'CO' AND LAST_MOD/86400 BETWEEN (SELECT AFTER_DATE/86400 FROM PARAMS) AND (SELECT BEFORE_DATE/86400 FROM PARAMS))
    ) AS WOS JOIN PERSON AS P WHERE WOS.PERSON_ID = P.ID



x/86400 BETWEEN STRFTIME('%s','--BEFORE_DATE--')/86400 AND STRFTIME('%s','--AFTER_DATE--')/86400

CASE STATUS_CODE WHEN 'CO' THEN DATETIME(LAST_MOD,'unixepoch') ELSE '' END AS DONE_DATE


SELECT * FROM (
SELECT ID, WORK_NO, LAST_MOD, STATUS_CODE AS DONE_DATE 
FROM WORK_ORDER
UNION
SELECT ID, WORK_NO, LAST_MOD, STATUS_CODE AS DONE_DATE 
FROM WORK_ORDER_HIST) AS WO


