--
-- File generated with SQLiteStudio v3.1.1 on Sr mar 7 12:42:59 2018
--
-- Text encoding used: System
--
-- Results of query:
-- SELECT PERSON_ID,
--        PERIOD_DATE,
--        LEAVE_TIME,
--        WORK_TIME,
--        POOL_WORK_TIME,
--        OVER_TIME,
--        LEAVE_DUE,
--        WORK_DUE,
--        OVER_DUE,
--        TOTAL_DUE,
--        IS_FROM_POOL,
--        RANK_CODE,
--        PROJECT_FACTOR,
--        POOL_RATE,
--        OVER_TIME_FACTOR,
--        APPROVED,
--        MODIFIED_BY,
--        LAST_MOD
--   FROM V_PAYROLL
--  WHERE PERSON_ID IN (129, 128)
--
BEGIN TRANSACTION;

CREATE TABLE MY_TEST_TABLE (
    PERSON_ID,
    PERIOD_DATE,
    LEAVE_TIME,
    WORK_TIME,
    POOL_WORK_TIME,
    OVER_TIME,
    LEAVE_DUE,
    WORK_DUE,
    OVER_DUE,
    TOTAL_DUE,
    IS_FROM_POOL,
    RANK_CODE,
    PROJECT_FACTOR,
    POOL_RATE,
    OVER_TIME_FACTOR,
    APPROVED,
    MODIFIED_BY,
    LAST_MOD
);

INSERT INTO MY_TEST_TABLE (PERSON_ID, PERIOD_DATE, LEAVE_TIME, WORK_TIME, POOL_WORK_TIME, OVER_TIME, LEAVE_DUE, WORK_DUE, OVER_DUE, TOTAL_DUE, IS_FROM_POOL, RANK_CODE, PROJECT_FACTOR, POOL_RATE, OVER_TIME_FACTOR, APPROVED, MODIFIED_BY, LAST_MOD) VALUES (128, '2017-12-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 'N', 'YOU', 1, 0.01, 1, '1', 5, '2018-03-07 10:31:58');
INSERT INTO MY_TEST_TABLE (PERSON_ID, PERIOD_DATE, LEAVE_TIME, WORK_TIME, POOL_WORK_TIME, OVER_TIME, LEAVE_DUE, WORK_DUE, OVER_DUE, TOTAL_DUE, IS_FROM_POOL, RANK_CODE, PROJECT_FACTOR, POOL_RATE, OVER_TIME_FACTOR, APPROVED, MODIFIED_BY, LAST_MOD) VALUES (128, '2018-02-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 'N', 'YOU', 1, -0.138, 2, 'Y', 137, '2018-03-07 11:34:26');
INSERT INTO MY_TEST_TABLE (PERSON_ID, PERIOD_DATE, LEAVE_TIME, WORK_TIME, POOL_WORK_TIME, OVER_TIME, LEAVE_DUE, WORK_DUE, OVER_DUE, TOTAL_DUE, IS_FROM_POOL, RANK_CODE, PROJECT_FACTOR, POOL_RATE, OVER_TIME_FACTOR, APPROVED, MODIFIED_BY, LAST_MOD) VALUES (129, '2017-12-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 'Y', 'REG', 0.8, 0.01, 1, '1', 5, '2018-03-07 10:31:58');
INSERT INTO MY_TEST_TABLE (PERSON_ID, PERIOD_DATE, LEAVE_TIME, WORK_TIME, POOL_WORK_TIME, OVER_TIME, LEAVE_DUE, WORK_DUE, OVER_DUE, TOTAL_DUE, IS_FROM_POOL, RANK_CODE, PROJECT_FACTOR, POOL_RATE, OVER_TIME_FACTOR, APPROVED, MODIFIED_BY, LAST_MOD) VALUES (129, '2018-02-01 00:00:00', 0, 0, 0, 0, 0, 0, 0, 0, 'Y', 'REG', 0.8, -0.138, 2, 'Y', 137, '2018-03-07 11:34:26');

COMMIT TRANSACTION;
PRAGMA foreign_keys = on;
