ALTER TABLE TIME_SHEET ADD COLUMN FROM_IP  VARCHAR(15);
ALTER TABLE TIME_SHEET ADD COLUMN FROM_ISP VARCHAR(100);
ALTER TABLE TIME_SHEET ADD COLUMN FROM_CITY VARCHAR(100);
ALTER TABLE TIME_SHEET ADD COLUMN FROM_IS_MOBILE VARCHAR(1);
ALTER TABLE TIME_SHEET ADD COLUMN TO_IP    VARCHAR(15);
ALTER TABLE TIME_SHEET ADD COLUMN TO_ISP   VARCHAR(100);
ALTER TABLE TIME_SHEET ADD COLUMN TO_CITY VARCHAR(100);
ALTER TABLE TIME_SHEET ADD COLUMN TO_IS_MOBILE VARCHAR(1);
