DROP TABLE IF EXISTS IP_GEO;
CREATE TABLE IP_GEO (
	IP VARCHAR(15) PRIMARY KEY ON CONFLICT IGNORE,
    ISP VARCHAR(80),
    ORG VARCHAR(80),
	CITY VARCHAR(80),
    REGION VARCHAR(80)
);

ALTER TABLE TIME_SHEET ADD COLUMN FROM_IP  VARCHAR(15) REFERENCES IP_GEO(IP);
ALTER TABLE TIME_SHEET ADD COLUMN FROM_IS_MOBILE VARCHAR(1);
ALTER TABLE TIME_SHEET ADD COLUMN TO_IP    VARCHAR(15) REFERENCES IP_GEO(IP);
ALTER TABLE TIME_SHEET ADD COLUMN TO_IS_MOBILE VARCHAR(1);
