DROP TRIGGER IF EXISTS LOG_WO;
CREATE TRIGGER LOG_WO BEFORE UPDATE ON WORK_ORDER
WHEN
    OLD.STATUS_CODE <> NEW.STATUS_CODE
BEGIN
    INSERT INTO WORK_ORDER_HIST ( ID, WORK_NO, STATUS_CODE, TYPE_CODE, OFFICE_CODE, COMMENT, MD_CAPEX, PROTOCOL_NO, IS_FROM_POOL, DESCRIPTION, COMPLEXITY_CODE, COMPLEXITY, PRICE, ITEM_ID, VENTURE_ID, MODIFIED_BY, CREATED, LAST_MOD, HIST_CREATED, ASSIGNED_ID )
    VALUES ( OLD.ID, OLD.WORK_NO, OLD.STATUS_CODE, OLD.TYPE_CODE, OLD.OFFICE_CODE, OLD.COMMENT, OLD.MD_CAPEX, OLD.PROTOCOL_NO, OLD.IS_FROM_POOL, OLD.DESCRIPTION, OLD.COMPLEXITY_CODE, OLD.COMPLEXITY, OLD.PRICE, OLD.ITEM_ID, OLD.VENTURE_ID, OLD.MODIFIED_BY, OLD.CREATED, OLD.LAST_MOD, STRFTIME('%s','NOW'), (SELECT GROUP_CONCAT(PW.PERSON_ID,'|') FROM PERSON_WO PW WHERE PW.WO_ID = OLD.ID));
    
    UPDATE WORK_ORDER 
    SET LAST_MOD = STRFTIME('%s','NOW')
    WHERE ID = OLD.ID;
END;

CREATE INDEX WORK_ORDER_LAST_MOD_IDX ON WORK_ORDER(LAST_MOD);
CREATE INDEX WORK_ORDER_STATUS_IDX ON WORK_ORDER(STATUS_CODE);