ALTER TABLE WORK_ORDER_HIST ADD COLUMN ASSIGNED_ID;
CREATE INDEX WORK_ORDER_HIST_ID_IDX ON WORK_ORDER_HIST(ID);
CREATE INDEX WORK_ORDER_HIST_LAST_MOD_IDX ON WORK_ORDER_HIST(LAST_MOD);
CREATE INDEX WORK_ORDER_HIST_STATUS_IDX ON WORK_ORDER_HIST(STATUS_CODE);